### ISSUE TITLE
Add a timer interrupt for preemptive scheduling

### ISSUE THREAD

**Issue by DerekCresswell** [KidneyOS/KidneyOS#28]
We must register a timer interrupt and handler on the IDT in order to allow for preemptive scheduling. All of the existing mechanics for switching are present. This should only be a handler made to call onto the yield functions of the scheduler.

The basic setup for the IDT is in place. Adding a handler for the timer will be similar to the existing handlers.

Note, this may require some direct assembly (paying attention to calling conventions) in order to correctly create the handler. Such as using the `iret` instruction for returning and ensuring we switch into and out of the kernel stack.

**Comment by mtoohey31** [comment]
Also, a note for the person who ends up working on this: once preemptive scheduling is working, we should probably review all the existing kernel code that might be executed while interrupts are enabled. Some of the existing code that's currently safe, given the assumption that it won't be called in a reentrant way, might have bugs that could arise once this assumption no longer holds, due to the introduction of preemptive scheduling.
